### ISSUE TITLE
文が改行されていない

### ISSUE THREAD

**Issue by maki-glenscape** [8amjp/descriptive-girl#1]
この『ディスクリプティブガール』の本文ページでは、pタグの中でbrタグが使われていないようです。そのため、同一pタグ内の会話文が１行に連なってしまったり、行頭字下げの全角空白が句点の直後に現れたりしています。

**Comment by 8amjp** [comment]
ありがとうございます。最初のページしかMarkDown化してませんでした。急いで直しました。
